### ISSUE TITLE
Issue in Octobercms Build 446

### ISSUE THREAD

**Issue by zakir1929** [SaifurRahmanMohsin/Txt-Plugin#21]
https://prnt.sc/m4hmep

**Comment by Balex70** [comment]
Facing the same problem!

**Comment by SaifurRahmanMohsin** [comment]
Hello. I verified that this error does not originate from this plugin. There is no substr function used at all. Kindly update your OctoberCMS to the latest revision as it works fine in that. If the issue persists, then feel free to re-open this issue but also describe the steps involved so I can re-create the bug at my end to fix it.
