### ISSUE TITLE
Entries duplicated when using 'save' rather than 'save and close'

### ISSUE THREAD

**Issue by RCheesley** [SaifurRahmanMohsin/txt-plugin#22]
When working with humans.txt I am finding multiple entries are being duplicated if I press 'save' (to continue working on it) rather than 'save and close'.

**Comment by mohsin** [comment]
@RCheesley This should be fixed now. Feel free to re-open the plugin with some more details (reproduction steps) if it doesn't. Thanks.

**Comment by RCheesley** [comment]
Great, but we haven't used OctoberCMS since 2019! :) Glad it's sorted!
