### ISSUE TITLE
Unable to delete an attribute

### ISSUE THREAD

**Issue by RCheesley** [SaifurRahmanMohsin/txt-plugin#24]
I accidentally created a second team attribute which I did not need. I wasn't able to delete it once it had been saved, even if I removed the items within it.

There doesn't seem to be any delete feature on the main list layout.

**Comment by SaifurRahmanMohsin** [comment]
Thanks for reporting this. Let me verify and get back to you.

**Comment by mohsin** [comment]
@RCheesley I've upgraded the plugin for OctoberCMS 2.0. This should work great now. Feel free to re-open the plugin with some details if it doesn't. Thanks.
