### ISSUE TITLE
i can't edit or add new Directive

### ISSUE THREAD

**Issue by syusakusai** [SaifurRahmanMohsin/txt-plugin#27]
Hi mohsin really love your plugins but today i cant add or edit my directive. 

Hope you can help me. thanks

**Comment by SaifurRahmanMohsin** [comment]
Thanks for reporting this. Let me verify this.

**Comment by mohsin** [comment]
@syusakusai I've upgraded the plugin for OctoberCMS 2.0. This should work great now. Feel free to re-open the plugin with some details if it doesn't. Thanks.
